# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1glZKu3be17FRXjCCou0jkW3r3-YwMuTO
"""

print("20")

a=10
b=20
c=a*b
print("product of a & b ",c)

a=3
b=3.14
c=a*b
print(c)
print(type(c))

T=int(input())
for i in range(T):
  n=int(input())
  k=int(input())
  print(k%n)

for x in range(1000):
  print("Hello World")

x,y=map(int,input().split()) # Expected input format: two space-separated numbers, e.g., '7 8'

if x < y:
  print("a < b")
elif x > y:
  print("a > b")
else:
  print("a == b")

x=int(input())
if x<10:
  print("Thanks for helping Chef!")
else:
  print("-1")

n=int(input())
k=int(input())
print(k%n)

w=int(input())
#w%2==0
if w>2 and w%2==0:
  print("YES")
else:
  print("NO")

T = int(input())

for _ in range(T):
    X = int(input())

    if 1 <= X <= 4:
        print("YES")
    else:
        print("NO")

T=int(input())
for _ in range(T):
  if c>20:
    print("COLD")
  else:
    print("HOT")

n=input()
print(n)

for i in range(1,100):
  print(i)

#right angle triangle
n=int(input())
for i in range(n):
  for j in range(i):
    print(j+i,end=" ")
  print(" ")

w=int(input())
l=int(input())
for i in range(w):
  for j in range(l):

    print(end=" * ")
  print(" ")

names=[]
names.append(1)
print(names)

names.insert(1,2)
print("names")

names=['h','e','l','l','o']
names.append(1)
names.insert(3,16)

print(names)

names.extend(['c','h','a','r','a','n'])
print(names)

names.pop()
print(names)T

list=[1,9,8]

for ali in list:
  if(ali>3 and ali<9):
    print(ali)

y=int(input())
print("y:",y)

clg=input()
print(f"clg name",{clg})

for i in range(1,10):
  print(i)

fruits=["apples","mango","grapes","watermelon","cherries"]
for n in fruits:
  print(n)

list=[1,2,3,4,5]
print(list)
list.append(6)
print(list)
list.remove(4)
print(list)

marks=[20,30,40,50]
print(max(marks))

n=int(input())
for i in range(n):
  for j in range(i):
    print(j+i,end=" ")
  print(" ")

w = int(input())
l = int(input())

for i in range(w):
    for j in range(l):

        if i == 0 or i == w-1 or j == 0 or j == l-1:
            print("*", end=" ")
        else:
            print(" ", end=" ")

    print()

n=int(input())
for i in range(n):
  for j in range(i+1):
    print()

x=int(input())
for i in range(1,11):
    print(x," * ", i," = ",x*i)

n = int(input())

arr = list(map(int, input().split()))

for i in range(n - 1, -1, -1):
    print(arr[i], end=" ")

#dictionary
clg={
    "name":"ksrm",
    "city":"kadapa",
    "pin":516005
}

print(clg)

print(clg["name"])
print(clg["pin"])

rank={1:"gold",2:"silver",3:"bronze"}
print(rank)
print(rank[3])

ksrm={
    "name":input(),
    "place":input()
}
print(ksrm)

person={

        "name":"sai",
        "id":21
}
print(person)

person["age"]=18
print(person)

info={
    "a":1,"b":2,"c":3,"d":4
}
info.keys()

da={
    "hi":"hello",
    "bye":"goodbye"
}
print(da)

for di in da.values():
  print(di)
for di in da:
  print(di)

value={1,2,3,4,4,5,5,5,6,6,6,6,6}
print(value)
value.add(7)
print(value)

value.remove(6)
print(value)

value.pop()
print(value)

value.clear()
print(value)

value.copy()
print(value)

x={1,2,3,3,4,5,6,6,6,4,5}
y={1,2,3,4,5,5,6,6,7,8,9}
print(x|y)
print(x.intersection(y))

print(x & y)

print(x-y)

print(x^y)

#problems
dept={
    "name":"cse",
    "block":"e",

}

print(dept)

dept["instock"]=True
print(dept)

dept["price"]=1000000
print(dept)

capital={
    "AP":"knl",
    "knt":"bang",
    "tam":"chn",
    "tel":"hyd",
    "up":"chn"
}

print(capital)
print(capital["AP"])

n={1,2,3,3,4,5,6,6,6,4,5,7,7,8,8,9}
p={1,2,3,4,5,5,6,6,7,8,7,5,9}
print(n)

print(n|p)
n.add(10)
print(n)

def charan():
  print("My name is charan")

print(charan())

#A Print Array
x=int(input())
arr=list(map(int, input().split()))
print(arr)

#B Summation
x=int(input())
arr=list(map(int, input().split()))
print(sum(arr))

#C Search with cops part_2
n=int(input())
a=[1 ,2, 3, 4 ,5 ,6, 7]
if n in a:
  print("Yes")
else:
  print("No")

#D Max one
n=int(input())
arr=list(map(int,input().split()))
print(arr.index(max(arr)))

#E Min array
x=int(input())
arr=list(map(int,input().split()))
print(arr.index(min(arr)))

y=int(input())
arr=list(map(int,input().split()))
if arr==arr[::-1]:
  print("Yes")
else:
  print("No")

